import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case simplifiedChinese = "zh-Hans"
    case traditionalChinese = "zh-Hant"
    case japanese = "ja"

    var id: String { rawValue }

    var locale: Locale {
        Locale(identifier: rawValue)
    }

    var displayName: String {
        switch self {
        case .english: "English"
        case .simplifiedChinese: "简体中文"
        case .traditionalChinese: "繁體中文"
        case .japanese: "日本語"
        }
    }

    static var selected: AppLanguage {
        AppLanguage(rawValue: UserDefaults.standard.string(forKey: "language") ?? "") ?? .english
    }
}

enum L10n {
    static func text(_ key: String, _ arguments: CVarArg...) -> String {
        let format = translations[AppLanguage.selected]?[key]
            ?? translations[.english]?[key]
            ?? key
        guard !arguments.isEmpty else { return format }
        return String(format: format, locale: AppLanguage.selected.locale, arguments: arguments)
    }

    private static let translations: [AppLanguage: [String: String]] = [
        .english: [
            "common.ok": "OK",
            "common.cancel": "Cancel",
            "common.save": "Save",
            "common.copy": "Copy",
            "common.clear": "Clear",
            "common.delete": "Delete",
            "common.edit": "Edit",
            "common.add": "Add",
            "common.connect": "Connect",
            "common.disconnect": "Disconnect",
            "common.reload": "Reload",
            "appearance": "Appearance",
            "appearance.system": "System",
            "appearance.light": "Light",
            "appearance.dark": "Dark",
            "language": "Language",
            "sidebar.overview": "Overview",
            "sidebar.proxies": "Proxies",
            "sidebar.connections": "Connections",
            "sidebar.logs": "Logs",
            "legacy.defaultGroup": "Default",
            "legacy.noConfiguration": "No legacy configuration was found at %@.",
            "legacy.profilesLoaded": "Loaded %@ profiles from %@.",
            "legacy.untitledGroup": "Untitled Group",
            "legacy.notConfigured": "Not configured",
            "profile.unavailable": "Unavailable",
            "profile.copyName": "%@ Copy",
            "core.available": "%@ Core available",
            "core.status.connected": "%@ Core connected",
            "core.status.unavailable": "%@ Core unavailable",
            "core.unavailableDetail": "Choose an executable for %@ in Settings to enable this Core.",
            "core.notExecutable": "The selected file is not executable.",
            "core.switchWhileRunning": "Stop the running Core before selecting another Core.",
            "xray.notFound": "Not found",
            "xray.unsupportedProtocol": "Xray does not support this profile type: %@.",
            "xray.unsupportedTransport": "Xray does not support this transport: %@.",
            "xray.missingCredential": "%@ is required before connecting.",
            "xray.invalidRealityTransport": "REALITY requires TCP, XHTTP, or gRPC transport.",
            "xray.missingRealityKey": "A REALITY public key is required before connecting.",
            "xray.executableNotFound": "No executable Xray Core was found. Choose the Xray executable in Settings.",
            "xray.notExecutable": "The selected file is not executable.",
            "xray.alreadyRunning": "The Xray Core is already running.",
            "xray.validationFailed": "Xray rejected the generated configuration: %@",
            "xray.launchFailed": "Could not start Xray: %@",
            "singbox.notFound": "Not found",
            "singbox.unsupportedProtocol": "sing-box does not support this profile type: %@.",
            "singbox.unsupportedTransport": "sing-box does not support this transport: %@.",
            "singbox.missingCredential": "%@ is required before connecting.",
            "singbox.missingRealityKey": "A REALITY public key is required before connecting.",
            "singbox.invalidEndpoint": "Enter a server address and port before connecting.",
            "singbox.executableNotFound": "No executable sing-box Core was found. Choose the sing-box executable in Settings.",
            "singbox.alreadyRunning": "The sing-box Core is already running.",
            "singbox.validationFailed": "sing-box rejected the generated configuration: %@",
            "singbox.launchFailed": "Could not start sing-box: %@",
            "download.releaseRequestFailed": "Could not load the official %@ GitHub release: %@",
            "download.assetUnavailable": "No compatible Apple Silicon asset was found in the official %@ release.",
            "download.checksumUnavailable": "The official %@ release did not provide a SHA-256 checksum.",
            "download.checksumMismatch": "The downloaded Core file did not match the official SHA-256 checksum.",
            "download.archiveExtractionFailed": "Could not extract the Core archive: %@",
            "download.executableMissing": "The downloaded %@ archive did not contain its executable.",
            "download.installationFailed": "Could not install the downloaded Core: %@",
            "state.nativeStorageReady": "Native profile storage is ready at %@.",
            "state.legacyProfilesReloaded": "Legacy profiles were reloaded.",
            "state.invalidProfile": "Enter a name, a server address, and a port from 1 to 65535.",
            "state.profileUpdated": "Updated %@.",
            "state.profileAdded": "Added %@.",
            "state.selectProxyToRemove": "Select a proxy to remove.",
            "state.legacyProfileReadOnly": "Legacy profiles are read-only. Use Edit to create an editable native copy.",
            "state.profileRemoved": "Removed %@.",
            "state.enterGroupName": "Enter a name for the group.",
            "state.groupCreated": "Created the %@ group.",
            "state.legacyGroupReadOnly": "Legacy groups are read-only.",
            "state.groupRenamed": "Renamed the group to %@.",
            "state.groupRemoved": "Removed the %@ group.",
            "state.selectProxyToConnect": "Select a proxy before connecting.",
            "state.profileStarted": "Started %@.",
            "state.connectionNotStarted": "Connection was not started: %@",
            "state.coreStopped": "Stopped the local Core service.",
            "state.coreSelected": "Selected %@ Core.",
            "state.stopCoreBeforeDownload": "Stop the running Core before downloading or replacing Core files.",
            "state.coreDownloaded": "Downloaded %@ Core %@ from GitHub.",
            "state.coreDownloadFailed": "Could not download %@ Core: %@",
            "state.coreStopFailed": "Core stop failed: %@",
            "state.selectProxyToTest": "Select a proxy before running a latency test.",
            "state.latencyUnavailable": "Latency testing becomes available when the native Core service is connected.",
            "state.latencyRequested": "Latency test requested before Core integration.",
            "state.systemServiceUnavailable": "System Proxy and VPN controls remain unavailable until the native Core and network-extension integrations are complete.",
            "state.selectProxyToCopy": "Select a proxy to copy its endpoint.",
            "state.endpointCopied": "Copied %@.",
            "state.endpointCopyLogged": "Copied the endpoint for %@.",
            "state.logsCopied": "Copied %@ log entries.",
            "state.logsCleared": "Cleared the activity log.",
            "state.saveFailed": "Could not save native profiles: %@",
            "state.storageFailed": "Native profile storage failed: %@",
            "sidebar.proxyGroups": "Proxy Groups",
            "sidebar.renameGroup": "Rename Group",
            "sidebar.deleteGroup": "Delete Group",
            "sidebar.newGroup": "New Group",
            "sidebar.newGroupHelp": "New Group",
            "toolbar.connectHelp": "Connect the selected proxy when the native Core is available.",
            "toolbar.reloadLegacyHelp": "Reload read-only legacy profiles.",
            "overview.subtitle": "Native profile management for macOS",
            "overview.manageProxies": "Manage Proxies",
            "overview.core": "Core",
            "overview.selectedProxy": "Selected Proxy",
            "overview.noSelection": "No selection",
            "overview.selectProxyHint": "Choose a proxy to connect or copy its endpoint.",
            "overview.profiles": "Profiles",
            "overview.nativeProfileCount": "%@ stored in native profile storage",
            "overview.activity": "Activity",
            "overview.recentEvents": "Recent local events are available in Logs.",
            "overview.quickActions": "Quick Actions",
            "overview.nativeProfile": "Native profile",
            "overview.legacyProfile": "Legacy profile",
            "overview.copyEndpoint": "Copy Endpoint",
            "overview.testLatency": "Test Latency",
            "overview.reloadImports": "Reload Imports",
            "overview.nativeProfileStorage": "Native profile storage",
            "overview.networkServices": "Network Services",
            "overview.coreRequired": "Core required",
            "overview.networkServicesDescription": "System Proxy, VPN Mode, inbound listeners, and connection inspection will become available after native Core integration.",
            "overview.showIntegrationStatus": "Show Integration Status",
            "table.name": "Name",
            "table.type": "Type",
            "table.latency": "Latency",
            "table.traffic": "Traffic",
            "proxies.search": "Search name, address, or type",
            "proxies.newProxy": "New Proxy",
            "proxies.makeEditableCopy": "Make Editable Copy",
            "proxies.selectProxyToEdit": "Select a proxy to edit.",
            "proxies.emptyGroup": "No Proxies in This Group",
            "proxies.emptySearch": "No Matching Proxies",
            "proxies.emptyGroupDescription": "Add a native proxy or reload the read-only legacy import.",
            "proxies.emptySearchDescription": "Try a different name, address, or proxy type.",
            "editor.newNativeProxy": "New Native Proxy",
            "editor.editNativeProxy": "Edit Native Proxy",
            "editor.storageNotice": "Saved only in NekoBox Application Support storage.",
            "editor.name": "Name",
            "editor.type": "Type",
            "editor.custom": "Custom",
            "editor.group": "Group",
            "editor.server": "Server",
            "editor.port": "Port",
            "editor.endpointPreview": "Endpoint preview",
            "editor.xraySettings": "Xray Settings",
            "editor.coreSettings": "Core Settings",
            "editor.userID": "UUID",
            "editor.password": "Password",
            "editor.method": "Encryption Method",
            "editor.flow": "Flow",
            "editor.transport": "Transport",
            "editor.transportSecurity": "Transport Security",
            "editor.securityNone": "None",
            "editor.path": "Path",
            "editor.host": "Host",
            "editor.serverName": "SNI",
            "editor.allowInsecure": "Allow Insecure TLS",
            "editor.fingerprint": "TLS Fingerprint",
            "editor.realityPublicKey": "REALITY Public Key",
            "editor.realityShortID": "REALITY Short ID",
            "editor.realitySpiderX": "REALITY Spider X",
            "editor.validFieldsRequired": "A name, server, and valid port are required.",
            "groupEditor.groupName": "Group name",
            "connections.noActive": "No Active Connections",
            "connections.emptyDescription": "Connection inspection will populate here when the native Core service is connected.",
            "connections.inbound": "Inbound",
            "connections.destination": "Destination",
            "connections.rule": "Rule",
            "connections.started": "Started",
            "logs.noActivity": "No Activity Yet",
            "logs.emptyDescription": "Profile changes and Core actions will appear here.",
            "settings.launchAtLogin": "Launch at Login",
            "settings.launchAtLoginDescription": "Launch at Login becomes available with the native app lifecycle integration.",
            "settings.general": "General",
            "settings.languageAndAppearance": "Language & Appearance",
            "settings.application": "Application",
            "settings.dataLocations": "Data Locations",
            "settings.legacyDataDescription": "Legacy configuration is imported read-only and is never changed by NekoBox.",
            "settings.core": "Core",
            "settings.coreManagement": "Core Management",
            "settings.coreManagementDescription": "Download official Apple Silicon Core builds from GitHub, or choose an existing executable.",
            "settings.activeCore": "Active Core",
            "settings.activeCoreDescription": "Stop the active Core before switching engines or replacing Core files.",
            "settings.active": "Active",
            "settings.coreReady": "Ready to use",
            "settings.coreNotInstalled": "Not installed",
            "settings.coreExecutable": "%@ executable",
            "settings.installedVersion": "Installed version",
            "settings.downloadCore": "Download %@",
            "settings.updateCore": "Update %@",
            "settings.downloadingCore": "Downloading %@ from GitHub…",
            "settings.chooseCoreExecutable": "Choose %@ Executable",
            "settings.useDetectedCore": "Use Automatically Detected %@",
            "settings.officialRelease": "Official GitHub Release",
            "settings.localEndpoints": "Local proxy endpoints",
            "settings.localEndpointsDescription": "When connected, configure an app or the system proxy to use one of these local endpoints.",
            "settings.legacyProfileLocation": "Legacy profile location",
            "settings.reloadLegacyProfiles": "Reload Legacy Profiles",
            "settings.xrayCore": "Xray Core",
            "settings.xrayExecutable": "Xray executable",
            "settings.chooseXrayExecutable": "Choose Xray Executable",
            "settings.useDetectedXray": "Use Automatically Detected Xray",
            "settings.xrayLocalEndpoints": "Local proxy endpoints",
            "settings.xrayLocalEndpointsDescription": "When connected, configure an app or the system proxy to use one of these local endpoints.",
            "commands.reloadProfiles": "Reload Profiles",
            "commands.connection": "Connection",
            "commands.connectSelectedProxy": "Connect Selected Proxy"
        ],
        .simplifiedChinese: [
            "common.ok": "好",
            "common.cancel": "取消",
            "common.save": "保存",
            "common.copy": "复制",
            "common.clear": "清除",
            "common.delete": "删除",
            "common.edit": "编辑",
            "common.add": "添加",
            "common.connect": "连接",
            "common.disconnect": "断开连接",
            "common.reload": "重新载入",
            "appearance": "外观",
            "appearance.system": "跟随系统",
            "appearance.light": "浅色",
            "appearance.dark": "深色",
            "language": "语言",
            "sidebar.overview": "概览",
            "sidebar.proxies": "代理",
            "sidebar.connections": "连接",
            "sidebar.logs": "日志",
            "legacy.defaultGroup": "默认",
            "legacy.noConfiguration": "在 %@ 未找到旧版配置。",
            "legacy.profilesLoaded": "已从 %@ 载入 %@ 个配置。",
            "legacy.untitledGroup": "未命名分组",
            "legacy.notConfigured": "未配置",
            "profile.unavailable": "不可用",
            "profile.copyName": "%@ 的副本",
            "core.available": "%@ Core 可用",
            "core.status.connected": "%@ Core 已连接",
            "core.status.unavailable": "%@ Core 不可用",
            "core.unavailableDetail": "请在设置中选择 %@ 可执行文件以启用该 Core。",
            "core.notExecutable": "所选文件不可执行。",
            "core.switchWhileRunning": "请先停止正在运行的 Core，再选择其他 Core。",
            "xray.notFound": "未找到",
            "xray.unsupportedProtocol": "Xray 不支持此配置类型：%@。",
            "xray.unsupportedTransport": "Xray 不支持此传输方式：%@。",
            "xray.missingCredential": "连接前必须填写 %@。",
            "xray.invalidRealityTransport": "REALITY 需要 TCP、XHTTP 或 gRPC 传输。",
            "xray.missingRealityKey": "连接前必须填写 REALITY 公钥。",
            "xray.executableNotFound": "未找到可执行的 Xray Core。请在设置中选择 Xray 可执行文件。",
            "xray.notExecutable": "所选文件不可执行。",
            "xray.alreadyRunning": "Xray Core 已在运行。",
            "xray.validationFailed": "Xray 拒绝了生成的配置：%@",
            "xray.launchFailed": "无法启动 Xray：%@",
            "singbox.notFound": "未找到",
            "singbox.unsupportedProtocol": "sing-box 不支持此配置类型：%@。",
            "singbox.unsupportedTransport": "sing-box 不支持此传输方式：%@。",
            "singbox.missingCredential": "连接前必须填写 %@。",
            "singbox.missingRealityKey": "连接前必须填写 REALITY 公钥。",
            "singbox.invalidEndpoint": "连接前请输入服务器地址和端口。",
            "singbox.executableNotFound": "未找到可执行的 sing-box Core。请在设置中选择 sing-box 可执行文件。",
            "singbox.alreadyRunning": "sing-box Core 已在运行。",
            "singbox.validationFailed": "sing-box 拒绝了生成的配置：%@",
            "singbox.launchFailed": "无法启动 sing-box：%@",
            "download.releaseRequestFailed": "无法读取 %@ 的官方 GitHub Release：%@",
            "download.assetUnavailable": "官方 %@ Release 中未找到兼容 Apple Silicon 的资源。",
            "download.checksumUnavailable": "官方 %@ Release 未提供 SHA-256 校验和。",
            "download.checksumMismatch": "下载的 Core 文件与官方 SHA-256 校验和不匹配。",
            "download.archiveExtractionFailed": "无法解压 Core 压缩包：%@",
            "download.executableMissing": "下载的 %@ 压缩包不包含可执行文件。",
            "download.installationFailed": "无法安装下载的 Core：%@",
            "state.nativeStorageReady": "原生配置存储已就绪：%@。",
            "state.legacyProfilesReloaded": "旧版配置已重新载入。",
            "state.invalidProfile": "请输入名称、服务器地址以及 1 到 65535 之间的端口。",
            "state.profileUpdated": "已更新 %@。",
            "state.profileAdded": "已添加 %@。",
            "state.selectProxyToRemove": "请选择要删除的代理。",
            "state.legacyProfileReadOnly": "旧版配置为只读。请使用“编辑”创建可编辑的原生副本。",
            "state.profileRemoved": "已删除 %@。",
            "state.enterGroupName": "请输入分组名称。",
            "state.groupCreated": "已创建分组 %@。",
            "state.legacyGroupReadOnly": "旧版分组为只读。",
            "state.groupRenamed": "分组已重命名为 %@。",
            "state.groupRemoved": "已删除分组 %@。",
            "state.selectProxyToConnect": "请先选择要连接的代理。",
            "state.profileStarted": "已启动 %@。",
            "state.connectionNotStarted": "连接未启动：%@",
            "state.coreStopped": "本地 Core 服务已停止。",
            "state.coreSelected": "已选择 %@ Core。",
            "state.stopCoreBeforeDownload": "下载或替换 Core 文件前，请先停止正在运行的 Core。",
            "state.coreDownloaded": "已从 GitHub 下载 %@ Core %@。",
            "state.coreDownloadFailed": "无法下载 %@ Core：%@",
            "state.coreStopFailed": "停止 Core 失败：%@",
            "state.selectProxyToTest": "请先选择要测试延迟的代理。",
            "state.latencyUnavailable": "原生 Core 服务连接后即可使用延迟测试。",
            "state.latencyRequested": "在 Core 集成完成前请求了延迟测试。",
            "state.systemServiceUnavailable": "在完成原生 Core 和网络扩展集成前，系统代理和 VPN 控制不可用。",
            "state.selectProxyToCopy": "请选择要复制端点的代理。",
            "state.endpointCopied": "已复制 %@。",
            "state.endpointCopyLogged": "已复制 %@ 的端点。",
            "state.logsCopied": "已复制 %@ 条日志。",
            "state.logsCleared": "活动日志已清除。",
            "state.saveFailed": "无法保存原生配置：%@",
            "state.storageFailed": "原生配置存储失败：%@",
            "sidebar.proxyGroups": "代理分组",
            "sidebar.renameGroup": "重命名分组",
            "sidebar.deleteGroup": "删除分组",
            "sidebar.newGroup": "新建分组",
            "sidebar.newGroupHelp": "新建分组",
            "toolbar.connectHelp": "原生 Core 可用后连接所选代理。",
            "toolbar.reloadLegacyHelp": "重新载入只读旧版配置。",
            "overview.subtitle": "macOS 原生配置管理",
            "overview.manageProxies": "管理代理",
            "overview.core": "Core",
            "overview.selectedProxy": "已选代理",
            "overview.noSelection": "未选择",
            "overview.selectProxyHint": "选择代理以连接或复制其端点。",
            "overview.profiles": "配置",
            "overview.nativeProfileCount": "原生配置存储中有 %@ 个",
            "overview.activity": "活动",
            "overview.recentEvents": "最近的本地事件可在日志中查看。",
            "overview.quickActions": "快捷操作",
            "overview.nativeProfile": "原生配置",
            "overview.legacyProfile": "旧版配置",
            "overview.copyEndpoint": "复制端点",
            "overview.testLatency": "测试延迟",
            "overview.reloadImports": "重新载入导入项",
            "overview.nativeProfileStorage": "原生配置存储",
            "overview.networkServices": "网络服务",
            "overview.coreRequired": "需要 Core",
            "overview.networkServicesDescription": "完成原生 Core 集成后，系统代理、VPN 模式、入站监听器和连接检查即可使用。",
            "overview.showIntegrationStatus": "显示集成状态",
            "table.name": "名称",
            "table.type": "类型",
            "table.latency": "延迟",
            "table.traffic": "流量",
            "proxies.search": "搜索名称、地址或类型",
            "proxies.newProxy": "新建代理",
            "proxies.makeEditableCopy": "创建可编辑副本",
            "proxies.selectProxyToEdit": "请选择要编辑的代理。",
            "proxies.emptyGroup": "此分组中没有代理",
            "proxies.emptySearch": "没有匹配的代理",
            "proxies.emptyGroupDescription": "添加原生代理或重新载入只读旧版配置。",
            "proxies.emptySearchDescription": "请尝试其他名称、地址或代理类型。",
            "editor.newNativeProxy": "新建原生代理",
            "editor.editNativeProxy": "编辑原生代理",
            "editor.storageNotice": "仅保存在 NekoBox 的 Application Support 存储中。",
            "editor.name": "名称",
            "editor.type": "类型",
            "editor.custom": "自定义",
            "editor.group": "分组",
            "editor.server": "服务器",
            "editor.port": "端口",
            "editor.endpointPreview": "端点预览",
            "editor.xraySettings": "Xray 设置",
            "editor.coreSettings": "Core 设置",
            "editor.userID": "UUID",
            "editor.password": "密码",
            "editor.method": "加密方法",
            "editor.flow": "流控",
            "editor.transport": "传输方式",
            "editor.transportSecurity": "传输安全",
            "editor.securityNone": "无",
            "editor.path": "路径",
            "editor.host": "主机",
            "editor.serverName": "SNI",
            "editor.allowInsecure": "允许不安全的 TLS",
            "editor.fingerprint": "TLS 指纹",
            "editor.realityPublicKey": "REALITY 公钥",
            "editor.realityShortID": "REALITY Short ID",
            "editor.realitySpiderX": "REALITY Spider X",
            "editor.validFieldsRequired": "必须填写名称、服务器和有效端口。",
            "groupEditor.groupName": "分组名称",
            "connections.noActive": "没有活动连接",
            "connections.emptyDescription": "原生 Core 服务连接后，连接检查会显示在这里。",
            "connections.inbound": "入站",
            "connections.destination": "目标地址",
            "connections.rule": "规则",
            "connections.started": "开始时间",
            "logs.noActivity": "暂无活动",
            "logs.emptyDescription": "配置变更和 Core 操作会显示在这里。",
            "settings.launchAtLogin": "登录时启动",
            "settings.launchAtLoginDescription": "完成原生应用生命周期集成后即可使用登录时启动。",
            "settings.general": "通用",
            "settings.languageAndAppearance": "语言与外观",
            "settings.application": "应用",
            "settings.dataLocations": "数据位置",
            "settings.legacyDataDescription": "旧版配置仅以只读方式导入，NekoBox 不会修改其内容。",
            "settings.core": "Core",
            "settings.coreManagement": "Core 管理",
            "settings.coreManagementDescription": "从 GitHub 下载官方 Apple Silicon Core，或选择现有可执行文件。",
            "settings.activeCore": "当前 Core",
            "settings.activeCoreDescription": "切换核心或替换 Core 文件前，请先停止正在运行的 Core。",
            "settings.active": "当前使用",
            "settings.coreReady": "可以使用",
            "settings.coreNotInstalled": "未安装",
            "settings.coreExecutable": "%@ 可执行文件",
            "settings.installedVersion": "已安装版本",
            "settings.downloadCore": "下载 %@",
            "settings.updateCore": "更新 %@",
            "settings.downloadingCore": "正在从 GitHub 下载 %@…",
            "settings.chooseCoreExecutable": "选择 %@ 可执行文件",
            "settings.useDetectedCore": "使用自动发现的 %@",
            "settings.officialRelease": "官方 GitHub Release",
            "settings.localEndpoints": "本地代理端点",
            "settings.localEndpointsDescription": "连接后，请将应用或系统代理配置为使用其中一个本地端点。",
            "settings.legacyProfileLocation": "旧版配置位置",
            "settings.reloadLegacyProfiles": "重新载入旧版配置",
            "settings.xrayCore": "Xray Core",
            "settings.xrayExecutable": "Xray 可执行文件",
            "settings.chooseXrayExecutable": "选择 Xray 可执行文件",
            "settings.useDetectedXray": "使用自动发现的 Xray",
            "settings.xrayLocalEndpoints": "本地代理端点",
            "settings.xrayLocalEndpointsDescription": "连接后，请将应用或系统代理配置为使用其中一个本地端点。",
            "commands.reloadProfiles": "重新载入配置",
            "commands.connection": "连接",
            "commands.connectSelectedProxy": "连接所选代理"
        ],
        .traditionalChinese: [
            "common.ok": "好",
            "common.cancel": "取消",
            "common.save": "儲存",
            "common.copy": "複製",
            "common.clear": "清除",
            "common.delete": "刪除",
            "common.edit": "編輯",
            "common.add": "加入",
            "common.connect": "連線",
            "common.disconnect": "中斷連線",
            "common.reload": "重新載入",
            "appearance": "外觀",
            "appearance.system": "跟隨系統",
            "appearance.light": "淺色",
            "appearance.dark": "深色",
            "language": "語言",
            "sidebar.overview": "總覽",
            "sidebar.proxies": "代理",
            "sidebar.connections": "連線",
            "sidebar.logs": "日誌",
            "legacy.defaultGroup": "預設",
            "legacy.noConfiguration": "在 %@ 找不到舊版設定。",
            "legacy.profilesLoaded": "已從 %@ 載入 %@ 個設定。",
            "legacy.untitledGroup": "未命名群組",
            "legacy.notConfigured": "未設定",
            "profile.unavailable": "無法使用",
            "profile.copyName": "%@ 的副本",
            "core.available": "%@ Core 可用",
            "core.status.connected": "%@ Core 已連線",
            "core.status.unavailable": "%@ Core 無法使用",
            "core.unavailableDetail": "請在設定中選擇 %@ 執行檔以啟用此 Core。",
            "core.notExecutable": "所選檔案不可執行。",
            "core.switchWhileRunning": "請先停止正在執行的 Core，再選擇其他 Core。",
            "xray.notFound": "找不到",
            "xray.unsupportedProtocol": "Xray 不支援此設定類型：%@。",
            "xray.unsupportedTransport": "Xray 不支援此傳輸方式：%@。",
            "xray.missingCredential": "連線前必須填寫 %@。",
            "xray.invalidRealityTransport": "REALITY 需要 TCP、XHTTP 或 gRPC 傳輸。",
            "xray.missingRealityKey": "連線前必須填寫 REALITY 公鑰。",
            "xray.executableNotFound": "找不到可執行的 Xray Core。請在設定中選擇 Xray 執行檔。",
            "xray.notExecutable": "所選檔案不可執行。",
            "xray.alreadyRunning": "Xray Core 已在執行。",
            "xray.validationFailed": "Xray 拒絕了產生的設定：%@",
            "xray.launchFailed": "無法啟動 Xray：%@",
            "singbox.notFound": "找不到",
            "singbox.unsupportedProtocol": "sing-box 不支援此設定類型：%@。",
            "singbox.unsupportedTransport": "sing-box 不支援此傳輸方式：%@。",
            "singbox.missingCredential": "連線前必須填寫 %@。",
            "singbox.missingRealityKey": "連線前必須填寫 REALITY 公鑰。",
            "singbox.invalidEndpoint": "連線前請輸入伺服器位址和連接埠。",
            "singbox.executableNotFound": "找不到可執行的 sing-box Core。請在設定中選擇 sing-box 執行檔。",
            "singbox.alreadyRunning": "sing-box Core 已在執行。",
            "singbox.validationFailed": "sing-box 拒絕了產生的設定：%@",
            "singbox.launchFailed": "無法啟動 sing-box：%@",
            "download.releaseRequestFailed": "無法讀取 %@ 的官方 GitHub Release：%@",
            "download.assetUnavailable": "官方 %@ Release 中找不到相容 Apple Silicon 的資源。",
            "download.checksumUnavailable": "官方 %@ Release 未提供 SHA-256 檢查碼。",
            "download.checksumMismatch": "下載的 Core 檔案與官方 SHA-256 檢查碼不符。",
            "download.archiveExtractionFailed": "無法解壓縮 Core 封存檔：%@",
            "download.executableMissing": "下載的 %@ 封存檔不包含可執行檔。",
            "download.installationFailed": "無法安裝下載的 Core：%@",
            "state.nativeStorageReady": "原生設定儲存已就緒：%@。",
            "state.legacyProfilesReloaded": "舊版設定已重新載入。",
            "state.invalidProfile": "請輸入名稱、伺服器位址，以及介於 1 到 65535 的連接埠。",
            "state.profileUpdated": "已更新 %@。",
            "state.profileAdded": "已加入 %@。",
            "state.selectProxyToRemove": "請選擇要刪除的代理。",
            "state.legacyProfileReadOnly": "舊版設定為唯讀。請使用「編輯」建立可編輯的原生副本。",
            "state.profileRemoved": "已刪除 %@。",
            "state.enterGroupName": "請輸入群組名稱。",
            "state.groupCreated": "已建立群組 %@。",
            "state.legacyGroupReadOnly": "舊版群組為唯讀。",
            "state.groupRenamed": "群組已重新命名為 %@。",
            "state.groupRemoved": "已刪除群組 %@。",
            "state.selectProxyToConnect": "請先選擇要連線的代理。",
            "state.profileStarted": "已啟動 %@。",
            "state.connectionNotStarted": "連線未啟動：%@",
            "state.coreStopped": "本機 Core 服務已停止。",
            "state.coreSelected": "已選擇 %@ Core。",
            "state.stopCoreBeforeDownload": "下載或替換 Core 檔案前，請先停止正在執行的 Core。",
            "state.coreDownloaded": "已從 GitHub 下載 %@ Core %@。",
            "state.coreDownloadFailed": "無法下載 %@ Core：%@",
            "state.coreStopFailed": "停止 Core 失敗：%@",
            "state.selectProxyToTest": "請先選擇要測試延遲的代理。",
            "state.latencyUnavailable": "原生 Core 服務連線後即可使用延遲測試。",
            "state.latencyRequested": "在 Core 整合完成前請求了延遲測試。",
            "state.systemServiceUnavailable": "完成原生 Core 和網路延伸功能整合前，系統代理和 VPN 控制無法使用。",
            "state.selectProxyToCopy": "請選擇要複製端點的代理。",
            "state.endpointCopied": "已複製 %@。",
            "state.endpointCopyLogged": "已複製 %@ 的端點。",
            "state.logsCopied": "已複製 %@ 筆日誌。",
            "state.logsCleared": "活動日誌已清除。",
            "state.saveFailed": "無法儲存原生設定：%@",
            "state.storageFailed": "原生設定儲存失敗：%@",
            "sidebar.proxyGroups": "代理群組",
            "sidebar.renameGroup": "重新命名群組",
            "sidebar.deleteGroup": "刪除群組",
            "sidebar.newGroup": "新增群組",
            "sidebar.newGroupHelp": "新增群組",
            "toolbar.connectHelp": "原生 Core 可用後連線所選代理。",
            "toolbar.reloadLegacyHelp": "重新載入唯讀的舊版設定。",
            "overview.subtitle": "macOS 原生設定管理",
            "overview.manageProxies": "管理代理",
            "overview.core": "Core",
            "overview.selectedProxy": "已選代理",
            "overview.noSelection": "未選擇",
            "overview.selectProxyHint": "選擇代理以連線或複製其端點。",
            "overview.profiles": "設定",
            "overview.nativeProfileCount": "原生設定儲存中有 %@ 個",
            "overview.activity": "活動",
            "overview.recentEvents": "最近的本機事件可在日誌中查看。",
            "overview.quickActions": "快速操作",
            "overview.nativeProfile": "原生設定",
            "overview.legacyProfile": "舊版設定",
            "overview.copyEndpoint": "複製端點",
            "overview.testLatency": "測試延遲",
            "overview.reloadImports": "重新載入匯入項目",
            "overview.nativeProfileStorage": "原生設定儲存",
            "overview.networkServices": "網路服務",
            "overview.coreRequired": "需要 Core",
            "overview.networkServicesDescription": "完成原生 Core 整合後，即可使用系統代理、VPN 模式、入站監聽器和連線檢查。",
            "overview.showIntegrationStatus": "顯示整合狀態",
            "table.name": "名稱",
            "table.type": "類型",
            "table.latency": "延遲",
            "table.traffic": "流量",
            "proxies.search": "搜尋名稱、位址或類型",
            "proxies.newProxy": "新增代理",
            "proxies.makeEditableCopy": "建立可編輯副本",
            "proxies.selectProxyToEdit": "請選擇要編輯的代理。",
            "proxies.emptyGroup": "此群組中沒有代理",
            "proxies.emptySearch": "沒有相符的代理",
            "proxies.emptyGroupDescription": "新增原生代理或重新載入唯讀的舊版設定。",
            "proxies.emptySearchDescription": "請嘗試其他名稱、位址或代理類型。",
            "editor.newNativeProxy": "新增原生代理",
            "editor.editNativeProxy": "編輯原生代理",
            "editor.storageNotice": "僅儲存在 NekoBox 的 Application Support 儲存空間中。",
            "editor.name": "名稱",
            "editor.type": "類型",
            "editor.custom": "自訂",
            "editor.group": "群組",
            "editor.server": "伺服器",
            "editor.port": "連接埠",
            "editor.endpointPreview": "端點預覽",
            "editor.xraySettings": "Xray 設定",
            "editor.coreSettings": "Core 設定",
            "editor.userID": "UUID",
            "editor.password": "密碼",
            "editor.method": "加密方法",
            "editor.flow": "流控",
            "editor.transport": "傳輸方式",
            "editor.transportSecurity": "傳輸安全",
            "editor.securityNone": "無",
            "editor.path": "路徑",
            "editor.host": "主機",
            "editor.serverName": "SNI",
            "editor.allowInsecure": "允許不安全的 TLS",
            "editor.fingerprint": "TLS 指紋",
            "editor.realityPublicKey": "REALITY 公鑰",
            "editor.realityShortID": "REALITY Short ID",
            "editor.realitySpiderX": "REALITY Spider X",
            "editor.validFieldsRequired": "必須填寫名稱、伺服器和有效連接埠。",
            "groupEditor.groupName": "群組名稱",
            "connections.noActive": "沒有作用中的連線",
            "connections.emptyDescription": "原生 Core 服務連線後，連線檢查會顯示在這裡。",
            "connections.inbound": "入站",
            "connections.destination": "目的地",
            "connections.rule": "規則",
            "connections.started": "開始時間",
            "logs.noActivity": "尚無活動",
            "logs.emptyDescription": "設定變更和 Core 操作會顯示在這裡。",
            "settings.launchAtLogin": "登入時啟動",
            "settings.launchAtLoginDescription": "完成原生應用程式生命週期整合後即可使用登入時啟動。",
            "settings.general": "一般",
            "settings.languageAndAppearance": "語言與外觀",
            "settings.application": "應用程式",
            "settings.dataLocations": "資料位置",
            "settings.legacyDataDescription": "舊版設定僅以唯讀方式匯入，NekoBox 不會修改其內容。",
            "settings.core": "Core",
            "settings.coreManagement": "Core 管理",
            "settings.coreManagementDescription": "從 GitHub 下載官方 Apple Silicon Core，或選擇現有可執行檔。",
            "settings.activeCore": "目前 Core",
            "settings.activeCoreDescription": "切換核心或替換 Core 檔案前，請先停止正在執行的 Core。",
            "settings.active": "目前使用",
            "settings.coreReady": "可以使用",
            "settings.coreNotInstalled": "未安裝",
            "settings.coreExecutable": "%@ 執行檔",
            "settings.installedVersion": "已安裝版本",
            "settings.downloadCore": "下載 %@",
            "settings.updateCore": "更新 %@",
            "settings.downloadingCore": "正在從 GitHub 下載 %@…",
            "settings.chooseCoreExecutable": "選擇 %@ 執行檔",
            "settings.useDetectedCore": "使用自動偵測的 %@",
            "settings.officialRelease": "官方 GitHub Release",
            "settings.localEndpoints": "本機代理端點",
            "settings.localEndpointsDescription": "連線後，請將應用程式或系統代理設定為使用其中一個本機端點。",
            "settings.legacyProfileLocation": "舊版設定位置",
            "settings.reloadLegacyProfiles": "重新載入舊版設定",
            "settings.xrayCore": "Xray Core",
            "settings.xrayExecutable": "Xray 執行檔",
            "settings.chooseXrayExecutable": "選擇 Xray 執行檔",
            "settings.useDetectedXray": "使用自動偵測的 Xray",
            "settings.xrayLocalEndpoints": "本機代理端點",
            "settings.xrayLocalEndpointsDescription": "連線後，請將應用程式或系統代理設定為使用其中一個本機端點。",
            "commands.reloadProfiles": "重新載入設定",
            "commands.connection": "連線",
            "commands.connectSelectedProxy": "連線所選代理"
        ],
        .japanese: [
            "common.ok": "OK",
            "common.cancel": "キャンセル",
            "common.save": "保存",
            "common.copy": "コピー",
            "common.clear": "消去",
            "common.delete": "削除",
            "common.edit": "編集",
            "common.add": "追加",
            "common.connect": "接続",
            "common.disconnect": "切断",
            "common.reload": "再読み込み",
            "appearance": "外観",
            "appearance.system": "システム設定",
            "appearance.light": "ライト",
            "appearance.dark": "ダーク",
            "language": "言語",
            "sidebar.overview": "概要",
            "sidebar.proxies": "プロキシ",
            "sidebar.connections": "接続",
            "sidebar.logs": "ログ",
            "legacy.defaultGroup": "デフォルト",
            "legacy.noConfiguration": "%@ にレガシー設定が見つかりませんでした。",
            "legacy.profilesLoaded": "%@ 件のプロファイルを %@ から読み込みました。",
            "legacy.untitledGroup": "無題のグループ",
            "legacy.notConfigured": "未設定",
            "profile.unavailable": "利用不可",
            "profile.copyName": "%@ のコピー",
            "core.available": "%@ Core を利用できます",
            "core.status.connected": "%@ Core 接続済み",
            "core.status.unavailable": "%@ Core を利用できません",
            "core.unavailableDetail": "この Core を有効にするには、設定で %@ 実行ファイルを選択してください。",
            "core.notExecutable": "選択したファイルは実行可能ではありません。",
            "core.switchWhileRunning": "別の Core を選択する前に、実行中の Core を停止してください。",
            "xray.notFound": "見つかりません",
            "xray.unsupportedProtocol": "Xray はこのプロファイル形式をサポートしていません: %@。",
            "xray.unsupportedTransport": "Xray はこのトランスポートをサポートしていません: %@。",
            "xray.missingCredential": "接続する前に %@ を入力してください。",
            "xray.invalidRealityTransport": "REALITY には TCP、XHTTP、または gRPC トランスポートが必要です。",
            "xray.missingRealityKey": "接続する前に REALITY 公開鍵を入力してください。",
            "xray.executableNotFound": "実行可能な Xray Core が見つかりません。設定で Xray 実行ファイルを選択してください。",
            "xray.notExecutable": "選択したファイルは実行可能ではありません。",
            "xray.alreadyRunning": "Xray Core はすでに実行中です。",
            "xray.validationFailed": "Xray が生成した設定を拒否しました: %@",
            "xray.launchFailed": "Xray を開始できませんでした: %@",
            "singbox.notFound": "見つかりません",
            "singbox.unsupportedProtocol": "sing-box はこのプロファイル形式をサポートしていません: %@。",
            "singbox.unsupportedTransport": "sing-box はこのトランスポートをサポートしていません: %@。",
            "singbox.missingCredential": "接続する前に %@ を入力してください。",
            "singbox.missingRealityKey": "接続する前に REALITY 公開鍵を入力してください。",
            "singbox.invalidEndpoint": "接続する前にサーバーアドレスとポートを入力してください。",
            "singbox.executableNotFound": "実行可能な sing-box Core が見つかりません。設定で sing-box 実行ファイルを選択してください。",
            "singbox.alreadyRunning": "sing-box Core はすでに実行中です。",
            "singbox.validationFailed": "sing-box が生成した設定を拒否しました: %@",
            "singbox.launchFailed": "sing-box を開始できませんでした: %@",
            "download.releaseRequestFailed": "公式 %@ GitHub Release を取得できませんでした: %@",
            "download.assetUnavailable": "公式 %@ Release に互換性のある Apple Silicon アセットがありません。",
            "download.checksumUnavailable": "公式 %@ Release に SHA-256 チェックサムがありません。",
            "download.checksumMismatch": "ダウンロードした Core ファイルが公式 SHA-256 チェックサムと一致しません。",
            "download.archiveExtractionFailed": "Core アーカイブを展開できませんでした: %@",
            "download.executableMissing": "ダウンロードした %@ アーカイブに実行ファイルがありません。",
            "download.installationFailed": "ダウンロードした Core をインストールできませんでした: %@",
            "state.nativeStorageReady": "ネイティブプロファイルストレージの準備ができました: %@。",
            "state.legacyProfilesReloaded": "レガシープロファイルを再読み込みしました。",
            "state.invalidProfile": "名前、サーバーアドレス、1～65535 のポートを入力してください。",
            "state.profileUpdated": "%@ を更新しました。",
            "state.profileAdded": "%@ を追加しました。",
            "state.selectProxyToRemove": "削除するプロキシを選択してください。",
            "state.legacyProfileReadOnly": "レガシープロファイルは読み取り専用です。「編集」で編集可能なネイティブコピーを作成してください。",
            "state.profileRemoved": "%@ を削除しました。",
            "state.enterGroupName": "グループ名を入力してください。",
            "state.groupCreated": "%@ グループを作成しました。",
            "state.legacyGroupReadOnly": "レガシーグループは読み取り専用です。",
            "state.groupRenamed": "グループ名を %@ に変更しました。",
            "state.groupRemoved": "%@ グループを削除しました。",
            "state.selectProxyToConnect": "接続するプロキシを選択してください。",
            "state.profileStarted": "%@ を開始しました。",
            "state.connectionNotStarted": "接続を開始できませんでした: %@",
            "state.coreStopped": "ローカル Core サービスを停止しました。",
            "state.coreSelected": "%@ Core を選択しました。",
            "state.stopCoreBeforeDownload": "Core ファイルをダウンロードまたは置き換える前に、実行中の Core を停止してください。",
            "state.coreDownloaded": "GitHub から %@ Core %@ をダウンロードしました。",
            "state.coreDownloadFailed": "%@ Core をダウンロードできませんでした: %@",
            "state.coreStopFailed": "Core を停止できませんでした: %@",
            "state.selectProxyToTest": "遅延をテストするプロキシを選択してください。",
            "state.latencyUnavailable": "ネイティブ Core サービスが接続されると遅延テストを利用できます。",
            "state.latencyRequested": "Core 統合前に遅延テストが要求されました。",
            "state.systemServiceUnavailable": "ネイティブ Core とネットワーク拡張機能の統合が完了するまで、システムプロキシと VPN の操作は利用できません。",
            "state.selectProxyToCopy": "エンドポイントをコピーするプロキシを選択してください。",
            "state.endpointCopied": "%@ をコピーしました。",
            "state.endpointCopyLogged": "%@ のエンドポイントをコピーしました。",
            "state.logsCopied": "%@ 件のログをコピーしました。",
            "state.logsCleared": "アクティビティログを消去しました。",
            "state.saveFailed": "ネイティブプロファイルを保存できませんでした: %@",
            "state.storageFailed": "ネイティブプロファイルの保存に失敗しました: %@",
            "sidebar.proxyGroups": "プロキシグループ",
            "sidebar.renameGroup": "グループ名を変更",
            "sidebar.deleteGroup": "グループを削除",
            "sidebar.newGroup": "新しいグループ",
            "sidebar.newGroupHelp": "新しいグループ",
            "toolbar.connectHelp": "ネイティブ Core を利用できる場合に、選択したプロキシへ接続します。",
            "toolbar.reloadLegacyHelp": "読み取り専用のレガシープロファイルを再読み込みします。",
            "overview.subtitle": "macOS 用ネイティブプロファイル管理",
            "overview.manageProxies": "プロキシを管理",
            "overview.core": "Core",
            "overview.selectedProxy": "選択中のプロキシ",
            "overview.noSelection": "未選択",
            "overview.selectProxyHint": "プロキシを選択して接続するか、エンドポイントをコピーしてください。",
            "overview.profiles": "プロファイル",
            "overview.nativeProfileCount": "ネイティブプロファイルストレージに %@ 件保存",
            "overview.activity": "アクティビティ",
            "overview.recentEvents": "最近のローカルイベントは「ログ」で確認できます。",
            "overview.quickActions": "クイックアクション",
            "overview.nativeProfile": "ネイティブプロファイル",
            "overview.legacyProfile": "レガシープロファイル",
            "overview.copyEndpoint": "エンドポイントをコピー",
            "overview.testLatency": "遅延をテスト",
            "overview.reloadImports": "インポートを再読み込み",
            "overview.nativeProfileStorage": "ネイティブプロファイルストレージ",
            "overview.networkServices": "ネットワークサービス",
            "overview.coreRequired": "Core が必要です",
            "overview.networkServicesDescription": "ネイティブ Core の統合後、システムプロキシ、VPN モード、受信リスナー、接続の検査を利用できます。",
            "overview.showIntegrationStatus": "統合状況を表示",
            "table.name": "名前",
            "table.type": "種類",
            "table.latency": "遅延",
            "table.traffic": "通信量",
            "proxies.search": "名前、アドレス、種類を検索",
            "proxies.newProxy": "新しいプロキシ",
            "proxies.makeEditableCopy": "編集可能なコピーを作成",
            "proxies.selectProxyToEdit": "編集するプロキシを選択してください。",
            "proxies.emptyGroup": "このグループにプロキシはありません",
            "proxies.emptySearch": "一致するプロキシはありません",
            "proxies.emptyGroupDescription": "ネイティブプロキシを追加するか、読み取り専用のレガシー設定を再読み込みしてください。",
            "proxies.emptySearchDescription": "別の名前、アドレス、プロキシの種類を試してください。",
            "editor.newNativeProxy": "新しいネイティブプロキシ",
            "editor.editNativeProxy": "ネイティブプロキシを編集",
            "editor.storageNotice": "NekoBox の Application Support ストレージにのみ保存されます。",
            "editor.name": "名前",
            "editor.type": "種類",
            "editor.custom": "カスタム",
            "editor.group": "グループ",
            "editor.server": "サーバー",
            "editor.port": "ポート",
            "editor.endpointPreview": "エンドポイントのプレビュー",
            "editor.xraySettings": "Xray 設定",
            "editor.coreSettings": "Core 設定",
            "editor.userID": "UUID",
            "editor.password": "パスワード",
            "editor.method": "暗号方式",
            "editor.flow": "Flow",
            "editor.transport": "トランスポート",
            "editor.transportSecurity": "トランスポートセキュリティ",
            "editor.securityNone": "なし",
            "editor.path": "パス",
            "editor.host": "ホスト",
            "editor.serverName": "SNI",
            "editor.allowInsecure": "安全でない TLS を許可",
            "editor.fingerprint": "TLS フィンガープリント",
            "editor.realityPublicKey": "REALITY 公開鍵",
            "editor.realityShortID": "REALITY Short ID",
            "editor.realitySpiderX": "REALITY Spider X",
            "editor.validFieldsRequired": "名前、サーバー、有効なポートが必要です。",
            "groupEditor.groupName": "グループ名",
            "connections.noActive": "アクティブな接続はありません",
            "connections.emptyDescription": "ネイティブ Core サービスの接続後、ここに接続情報が表示されます。",
            "connections.inbound": "受信",
            "connections.destination": "宛先",
            "connections.rule": "ルール",
            "connections.started": "開始時刻",
            "logs.noActivity": "アクティビティはまだありません",
            "logs.emptyDescription": "プロファイルの変更と Core の操作がここに表示されます。",
            "settings.launchAtLogin": "ログイン時に起動",
            "settings.launchAtLoginDescription": "ネイティブアプリのライフサイクル統合後に「ログイン時に起動」を利用できます。",
            "settings.general": "一般",
            "settings.languageAndAppearance": "言語と外観",
            "settings.application": "アプリケーション",
            "settings.dataLocations": "データの場所",
            "settings.legacyDataDescription": "レガシー設定は読み取り専用でインポートされ、NekoBox によって変更されることはありません。",
            "settings.core": "Core",
            "settings.coreManagement": "Core 管理",
            "settings.coreManagementDescription": "GitHub から公式 Apple Silicon Core をダウンロードするか、既存の実行ファイルを選択します。",
            "settings.activeCore": "使用する Core",
            "settings.activeCoreDescription": "エンジンの切り替えまたは Core ファイルの置き換え前に、実行中の Core を停止してください。",
            "settings.active": "使用中",
            "settings.coreReady": "使用可能",
            "settings.coreNotInstalled": "未インストール",
            "settings.coreExecutable": "%@ 実行ファイル",
            "settings.installedVersion": "インストール済みバージョン",
            "settings.downloadCore": "%@ をダウンロード",
            "settings.updateCore": "%@ を更新",
            "settings.downloadingCore": "GitHub から %@ をダウンロード中…",
            "settings.chooseCoreExecutable": "%@ 実行ファイルを選択",
            "settings.useDetectedCore": "自動検出した %@ を使用",
            "settings.officialRelease": "公式 GitHub Release",
            "settings.localEndpoints": "ローカルプロキシエンドポイント",
            "settings.localEndpointsDescription": "接続後、アプリまたはシステムのプロキシをこれらのローカルエンドポイントのいずれかに設定してください。",
            "settings.legacyProfileLocation": "レガシープロファイルの場所",
            "settings.reloadLegacyProfiles": "レガシープロファイルを再読み込み",
            "settings.xrayCore": "Xray Core",
            "settings.xrayExecutable": "Xray 実行ファイル",
            "settings.chooseXrayExecutable": "Xray 実行ファイルを選択",
            "settings.useDetectedXray": "自動検出した Xray を使用",
            "settings.xrayLocalEndpoints": "ローカルプロキシエンドポイント",
            "settings.xrayLocalEndpointsDescription": "接続後、アプリまたはシステムのプロキシをこれらのローカルエンドポイントのいずれかに設定してください。",
            "commands.reloadProfiles": "プロファイルを再読み込み",
            "commands.connection": "接続",
            "commands.connectSelectedProxy": "選択したプロキシに接続"
        ]
    ]
}
